# Generated by Django 6.0.1 on 2026-01-25 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_appointment_date_booking_appointment_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-request_date'], 'verbose_name': 'Booking/Inquiry', 'verbose_name_plural': 'Bookings & Inquiries'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='agent_response',
            field=models.TextField(blank=True, help_text='The reply sent by the agent', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='True if the agent has processed the request'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(help_text="User's initial inquiry or requirements"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.property'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='response_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Available', 'Available'), ('Sold', 'Sold'), ('Reserved', 'Reserved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
