# Generated by Django 6.0.1 on 2026-01-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_booking_options_alter_booking_agent_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='map_url',
            field=models.URLField(blank=True, help_text='Link from Google Maps', max_length=500, null=True),
        ),
    ]
