# Generated by Django 6.0.1 on 2026-01-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_ddress_property_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='panorama_360',
            field=models.ImageField(blank=True, help_text='Upload an equirectangular 360-degree image', null=True, upload_to='panoramas/'),
        ),
    ]
